Reindented

diff --git a/Neovim/plugins b/Neovim/plugins
--- a/Neovim/plugins
+++ b/Neovim/plugins
@@ -7,8 +7,8 @@
 # Check if Git is installed
 command -v git >/dev/null 2>&1
 if [ ! $? -eq 0 ]; then
-	echo "Git must be installed to run this script. Aborting."
-	exit 1
+  echo "Git must be installed to run this script. Aborting."
+  exit 1
 fi
 
 ###############################
@@ -18,5 +18,5 @@ fi
 NVIM_PLUGINS=~/.config/nvim/bundle
 
 if [ ! -d $NVIM_PLUGINS/vim-colors-solarized ]; then
-	git clone git://github.com/altercation/vim-colors-solarized.git $NVIM_PLUGINS/vim-colors-solarized
+  git clone git://github.com/altercation/vim-colors-solarized.git $NVIM_PLUGINS/vim-colors-solarized
 fi
